import type { Unidade } from "@/types/Entities";

const unidadesDestaque: Unidade[] = [
  {
    id: "1",
    name: "Hospital Santa Helena",
    type: "hospital",
    address: {
      street: "Rua Vergueiro",
      number: "2941",
      complement: "Vila Mariana",
      city: "São Paulo",
      state: "SP",
      zipCode: "",
    },
    specialties: [
      "Cardiologia",
      "Ortopedia",
      "Pediatria",
      "Neurologia",
      "Dermatologia",
      "Clínica Geral",
    ],
    hours: [],
    photos: ["/assets/units/santa-helena.jpg"],
    rating: 4.8,
    reviewCount: 1240,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: true,
  },
  {
    id: "2",
    name: "Clínica Viva Bem",
    type: "clinica",
    address: {
      street: "Av. Paulista",
      number: "1420",
      complement: "Bela Vista",
      city: "São Paulo",
      state: "SP",
      zipCode: "",
    },
    specialties: ["Clínica Geral", "Dermatologia"],
    hours: [],
    photos: ["/assets/units/viva-bem.jpg"],
    rating: 4.6,
    reviewCount: 687,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: true,
  },
  {
    id: "3",
    name: "Pronto Atendimento Saúde+",
    type: "pronto_atendimento",
    address: {
      street: "Rua dos Pinheiros",
      number: "890",
      complement: "Pinheiros",
      city: "São Paulo",
      state: "SP",
      zipCode: "",
    },
    specialties: ["Emergência", "Clínica Geral"],
    hours: [],
    photos: ["/assets/units/saude-mais.jpg"],
    rating: 4.4,
    reviewCount: 932,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: true,
  },
  {
    id: "4",
    name: "Hospital São Lucas",
    type: "hospital",
    address: {
      street: "Av. Paulista",
      number: "500",
      complement: "Bela Vista",
      city: "São Paulo",
      state: "SP",
      zipCode: "",
    },
    specialties: ["Cardiologia", "Neurologia"],
    hours: [],
    photos: ["/assets/units/sao-lucas.jpg"],
    rating: 4.7,
    reviewCount: 450,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: true,
  },
  {
    id: "5",
    name: "Clínica Horizonte",
    type: "clinica",
    address: {
      street: "Rua Augusta",
      number: "300",
      complement: "Consolação",
      city: "São Paulo",
      state: "SP",
      zipCode: "",
    },
    specialties: ["Pediatria", "Dermatologia"],
    hours: [],
    photos: ["/assets/units/horizonte.jpg"],
    rating: 4.9,
    reviewCount: 210,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: false,
  },
  {
    id: "6",
    name: "Instituto Vida",
    type: "clinica",
    address: {
      street: "Rua Oscar Freire",
      number: "1000",
      complement: "Jardins",
      city: "São Paulo",
      state: "SP",
      zipCode: "",
    },
    specialties: ["Cardiologia", "Clínica Geral"],
    hours: [],
    photos: ["/assets/units/instituto-vida.jpg"],
    rating: 5.0,
    reviewCount: 150,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: true,
  },
  {
    id: "7",
    name: "Hospital das Clínicas",
    type: "hospital",
    address: {
      street: "Av. Dr. Enéas",
      number: "255",
      complement: "Cerqueira César",
      city: "São Paulo",
      state: "SP",
      zipCode: "",
    },
    specialties: ["Emergência", "Ortopedia", "Neurologia"],
    hours: [],
    photos: ["/assets/units/hospital-clinicas.jpg"],
    rating: 4.5,
    reviewCount: 2104,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: true,
  },
  {
    id: "8",
    name: "Clínica Jardim Saúde",
    type: "clinica",
    address: {
      street: "Rua Visconde de Pirajá",
      number: "330",
      complement: "Ipanema",
      city: "Rio de Janeiro",
      state: "RJ",
      zipCode: "",
    },
    specialties: ["Clínica Geral"],
    hours: [],
    photos: ["/assets/units/jardim-saude.jpg"],
    rating: 4.3,
    reviewCount: 318,
    status: "rascunho",
    approval: "pendente",
    featured: true,
    openNow: true,
  },
  {
    id: "9",
    name: "Hospital Belo Horizonte",
    type: "hospital",
    address: {
      street: "Av. Afonso Pena",
      number: "1500",
      complement: "Centro",
      city: "Belo Horizonte",
      state: "MG",
      zipCode: "",
    },
    specialties: ["Emergência", "Cardiologia"],
    hours: [],
    photos: ["/assets/units/bh.jpg"],
    rating: 4.2,
    reviewCount: 540,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: true,
  },
  {
    id: "10",
    name: "Clínica Brasília Norte",
    type: "clinica",
    address: {
      street: "SQN 202, Bloco A",
      number: "",
      complement: "Asa Norte",
      city: "Brasília",
      state: "DF",
      zipCode: "",
    },
    specialties: ["Pediatria"],
    hours: [],
    photos: ["/assets/units/brasilia-norte.jpg"],
    rating: 4.6,
    reviewCount: 198,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: true,
  },
  {
    id: "11",
    name: "Pronto Socorro Central",
    type: "pronto_atendimento",
    address: {
      street: "Rua da Consolação",
      number: "80",
      complement: "Centro",
      city: "São Paulo",
      state: "SP",
      zipCode: "",
    },
    specialties: ["Emergência"],
    hours: [],
    photos: ["/assets/units/pronto-socorro.jpg"],
    rating: 4.1,
    reviewCount: 870,
    status: "rascunho",
    approval: "pendente",
    featured: true,
    openNow: true,
  },
  {
    id: "12",
    name: "Instituto Coração Livre",
    type: "clinica",
    address: {
      street: "Av. Jabaquara",
      number: "2100",
      complement: "Saúde",
      city: "São Paulo",
      state: "SP",
      zipCode: "",
    },
    specialties: ["Cardiologia"],
    hours: [],
    photos: ["/assets/units/coracao-livre.jpg"],
    rating: 4.8,
    reviewCount: 276,
    status: "publicado",
    approval: "aprovado",
    featured: true,
    openNow: true,
  },
];

export default unidadesDestaque;
